language: c++
sudo: required
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: h3SeiGB3WfrfbIIwtHR79GdMQAGBuVXCRNnUdeLhzTiZSE9pr3YTtQ6rNZuV1L++HmoaydMUow+MUg+Psga7nbn3bZndKA0qm1Ef8tuLja/nrkdnr1TpOcjPEJgar9dtHyhvcAZpayhu77lbQp2hwj4cGUq+mkR6v2i+Gyzooj/Ne8T2wNKOfD88AFXo2v1NYIS/V5aCEBytga+udfet+mG1j7p3Mx4DUxDh5G7SCkZDHM1siVHNTa2nsHFq1OvUqucfZgr9n2gYWMU0TXzUSfYiAQ0RppbaX4ZXLjtM5mFTc08FxIaXeblPouVZ8A2U7q5B3T7NiVzYRPoihnTJBthxWy6Mzi/MjxVkndre5rcogzhs8aX5c/1/UTAJHHsvpaLz2I9AcAmz74uwQybXRJntBccm7mehFajg5amPul8wnm/f/22kyOqeWVpmfMCgUJJpfXmOvAOooS+XYD7zstsaNND8lnE23VZ5Zt4XYss0H68bek2Lk+sdm4w/vq5YOBZQiqrEb7hN3xrctE5J+FOvhcorLGZrqvgoOO2bYq4k2F/fpnl0rj8VNuUmaj95Y3ewl9tfHF8Xcc04wjNT76NO2xBUmj3kqPOz40xCeIHxsPM0Jw7h3DfwclY9tQBXGJ/wTOAxLq6I0EPDr7ZEwAohNH5aJ32BFDSYJDxVV4k=


matrix:
  include:

   ## ###### Ubuntu Linux ####################################################

   ## ====== Ubuntu 19.10 (Eoan Ermine) ======================================
   #- name: "Ubuntu 19.10 (Eoan Ermine) with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   #- name: "Ubuntu 19.10 (Eoan Ermine) with Clang"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Ubuntu 19.10 (Eoan Ermine) packaging with pbuilder"
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="pbuilder"

   ## ====== Ubuntu 19.04 (Disco Dingo) ======================================
   #- name: "Ubuntu 19.04 (Disco Dingo) with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:disco" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ##- name: "Ubuntu 19.04 (Disco Dingo) with Clang"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="ubuntu:disco" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Ubuntu 19.04 (Disco Dingo) packaging with pbuilder"
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:disco" VARIANT="ubuntu" TOOL="pbuilder"

   ## ====== Ubuntu 18.04 (Bionic Beaver) ====================================
   #- name: "Ubuntu 18.04 (Bionic Beaver) with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ##- name: "Ubuntu 18.04 (Bionic Beaver) with Clang"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Ubuntu 18.04 (Bionic Beaver) packaging with pbuilder"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

   ## ====== Ubuntu 16.04 (Xenial Xerus) =====================================
   #- name: "Ubuntu 16.04 (Xenial Xerus) with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ##- name: "Ubuntu 16.04 (Xenial Xerus) with Clang"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Ubuntu 16.04 (Xenial Xerus) packaging with pbuilder"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"


   ## ###### Fedora Linux ###################################################

   ### ====== Fedora 31 =======================================================
   ##- name: "Fedora 31 with GCC"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="fedora:31" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ###- name: "Fedora 31 with Clang"
     ###os: linux
     ###dist: bionic
     ###group: travis_latest
     ###env: DOCKER="fedora:31" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   ##- name: "Fedora 31 packaging with mock"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="fedora:31" VARIANT="fedora" TOOL="mock"

   ## ====== Fedora 30 =======================================================
   #- name: "Fedora 30 with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:30" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ##- name: "Fedora 30 with Clang"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="fedora:30" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Fedora 30 packaging with mock"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:30" VARIANT="fedora" TOOL="mock"

   ## ====== Fedora 29 =======================================================
   #- name: "Fedora 29 with GCC"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:29" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ##- name: "Fedora 29 with Clang"
     ##os: linux
     ##dist: bionic
     ##group: travis_latest
     ##env: DOCKER="fedora:29" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   #- name: "Fedora 29 packaging with mock"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: DOCKER="fedora:29" VARIANT="fedora" TOOL="mock"

   ## ====== Fedora Rawhide ==================================================
   ## - name: "Fedora Rawhide with GCC"
   ##   os: linux
   ##   dist: bionic
   ##   group: travis_latest
   ##   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   ## - name: "Fedora Rawhide with Clang"
   ##   os: linux
   ##   dist: bionic
   ##   group: travis_latest
   ##   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   ## - name: "Fedora Rawhide packaging with mock"
   ##   os: linux
   ##   dist: bionic
   ##   group: travis_latest
   ##   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


   ## ###### Other ###########################################################

   ## ====== MacOS X ========================================================
   ## - name: "MacOS X"
   ##   os: osx
   ##   osx_image: xcode9.4
   ##   compiler: clang
   ##   group: travis_latest


   ## ###### Special #########################################################

   #- name: "Default Build"
     #os: linux
     #dist: bionic
     #group: travis_latest
     #env: TOOL="compile"

   - name: "Coverity Scan"
     os: linux
     dist: bionic
     group: travis_latest
     env:
      - TOOL="coverity"
      - VARIANT="ubuntu"
      - COVERITY_PROJECT="AtlasMNS+Trace"
      - COVERITY_SCAN_NOTIFICATION_EMAIL="dreibh@simula.no"
      - COVERITY_SCAN_BRANCH="coverity_scan"


before_install:
  - ci/before-install

install:
  - ci/install

script:
  - ci/build
  - |
    if [ "${VARIANT}" != "debian" ] ; then   # There is no Debian PPA for the required rsplib-* packages!
       ci/test
    fi
